/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ConfirmedRouteImport } from './routes/confirmed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthedAppRouteImport } from './routes/_authed.app'
import { Route as AuthedIntegrationsRouteImport } from './routes/_authed.integrations'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedTeamRouteImport } from './routes/_authed.team'
import { Route as AuthedWelcomeRouteImport } from './routes/_authed.welcome'
import { Route as AuthedAgentsAgentIdRouteImport } from './routes/_authed.agents.$agentId'
import { Route as AuthedAgentsAgentIdIndexRouteImport } from './routes/_authed.agents.$agentId.index'
import { Route as AuthedAgentsAgentIdChatRouteImport } from './routes/_authed.agents.$agentId.chat'
import { Route as AuthedAgentsAgentIdConfigurationRouteImport } from './routes/_authed.agents.$agentId.configuration'
import { Route as AuthedAgentsAgentIdKnowledgeRouteImport } from './routes/_authed.agents.$agentId.knowledge'
import { Route as AuthedAgentsAgentIdSettingsRouteImport } from './routes/_authed.agents.$agentId.settings'
import { Route as AuthedAgentsAgentIdRoutinesIndexRouteImport } from './routes/_authed.agents.$agentId.routines.index'
import { Route as AuthedAgentsAgentIdRoutinesRoutineIdRouteImport } from './routes/_authed.agents.$agentId.routines.$routineId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIntegrationsRoute = AuthedIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeamRoute = AuthedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWelcomeRoute = AuthedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsAgentIdRoute = AuthedAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsAgentIdIndexRoute =
  AuthedAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAgentsAgentIdRoute,
  } as any)
const AuthedAgentsAgentIdChatRoute = AuthedAgentsAgentIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedAgentsAgentIdRoute,
} as any)
const AuthedAgentsAgentIdConfigurationRoute =
  AuthedAgentsAgentIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthedAgentsAgentIdRoute,
  } as any)
const AuthedAgentsAgentIdKnowledgeRoute =
  AuthedAgentsAgentIdKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthedAgentsAgentIdRoute,
  } as any)
const AuthedAgentsAgentIdSettingsRoute =
  AuthedAgentsAgentIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedAgentsAgentIdRoute,
  } as any)
const AuthedAgentsAgentIdRoutinesIndexRoute =
  AuthedAgentsAgentIdRoutinesIndexRouteImport.update({
    id: '/routines/',
    path: '/routines/',
    getParentRoute: () => AuthedAgentsAgentIdRoute,
  } as any)
const AuthedAgentsAgentIdRoutinesRoutineIdRoute =
  AuthedAgentsAgentIdRoutinesRoutineIdRouteImport.update({
    id: '/routines/$routineId',
    path: '/routines/$routineId',
    getParentRoute: () => AuthedAgentsAgentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmed': typeof ConfirmedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthedAppRoute
  '/integrations': typeof AuthedIntegrationsRoute
  '/settings': typeof AuthedSettingsRoute
  '/team': typeof AuthedTeamRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/agents/$agentId': typeof AuthedAgentsAgentIdRouteWithChildren
  '/agents/$agentId/chat': typeof AuthedAgentsAgentIdChatRoute
  '/agents/$agentId/configuration': typeof AuthedAgentsAgentIdConfigurationRoute
  '/agents/$agentId/knowledge': typeof AuthedAgentsAgentIdKnowledgeRoute
  '/agents/$agentId/settings': typeof AuthedAgentsAgentIdSettingsRoute
  '/agents/$agentId/': typeof AuthedAgentsAgentIdIndexRoute
  '/agents/$agentId/routines/$routineId': typeof AuthedAgentsAgentIdRoutinesRoutineIdRoute
  '/agents/$agentId/routines/': typeof AuthedAgentsAgentIdRoutinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmed': typeof ConfirmedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthedAppRoute
  '/integrations': typeof AuthedIntegrationsRoute
  '/settings': typeof AuthedSettingsRoute
  '/team': typeof AuthedTeamRoute
  '/welcome': typeof AuthedWelcomeRoute
  '/agents/$agentId/chat': typeof AuthedAgentsAgentIdChatRoute
  '/agents/$agentId/configuration': typeof AuthedAgentsAgentIdConfigurationRoute
  '/agents/$agentId/knowledge': typeof AuthedAgentsAgentIdKnowledgeRoute
  '/agents/$agentId/settings': typeof AuthedAgentsAgentIdSettingsRoute
  '/agents/$agentId': typeof AuthedAgentsAgentIdIndexRoute
  '/agents/$agentId/routines/$routineId': typeof AuthedAgentsAgentIdRoutinesRoutineIdRoute
  '/agents/$agentId/routines': typeof AuthedAgentsAgentIdRoutinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/confirmed': typeof ConfirmedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/_authed/app': typeof AuthedAppRoute
  '/_authed/integrations': typeof AuthedIntegrationsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/team': typeof AuthedTeamRoute
  '/_authed/welcome': typeof AuthedWelcomeRoute
  '/_authed/agents/$agentId': typeof AuthedAgentsAgentIdRouteWithChildren
  '/_authed/agents/$agentId/chat': typeof AuthedAgentsAgentIdChatRoute
  '/_authed/agents/$agentId/configuration': typeof AuthedAgentsAgentIdConfigurationRoute
  '/_authed/agents/$agentId/knowledge': typeof AuthedAgentsAgentIdKnowledgeRoute
  '/_authed/agents/$agentId/settings': typeof AuthedAgentsAgentIdSettingsRoute
  '/_authed/agents/$agentId/': typeof AuthedAgentsAgentIdIndexRoute
  '/_authed/agents/$agentId/routines/$routineId': typeof AuthedAgentsAgentIdRoutinesRoutineIdRoute
  '/_authed/agents/$agentId/routines/': typeof AuthedAgentsAgentIdRoutinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmed'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/app'
    | '/integrations'
    | '/settings'
    | '/team'
    | '/welcome'
    | '/agents/$agentId'
    | '/agents/$agentId/chat'
    | '/agents/$agentId/configuration'
    | '/agents/$agentId/knowledge'
    | '/agents/$agentId/settings'
    | '/agents/$agentId/'
    | '/agents/$agentId/routines/$routineId'
    | '/agents/$agentId/routines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmed'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/app'
    | '/integrations'
    | '/settings'
    | '/team'
    | '/welcome'
    | '/agents/$agentId/chat'
    | '/agents/$agentId/configuration'
    | '/agents/$agentId/knowledge'
    | '/agents/$agentId/settings'
    | '/agents/$agentId'
    | '/agents/$agentId/routines/$routineId'
    | '/agents/$agentId/routines'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/confirmed'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/_authed/app'
    | '/_authed/integrations'
    | '/_authed/settings'
    | '/_authed/team'
    | '/_authed/welcome'
    | '/_authed/agents/$agentId'
    | '/_authed/agents/$agentId/chat'
    | '/_authed/agents/$agentId/configuration'
    | '/_authed/agents/$agentId/knowledge'
    | '/_authed/agents/$agentId/settings'
    | '/_authed/agents/$agentId/'
    | '/_authed/agents/$agentId/routines/$routineId'
    | '/_authed/agents/$agentId/routines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ConfirmedRoute: typeof ConfirmedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/integrations': {
      id: '/_authed/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthedIntegrationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/team': {
      id: '/_authed/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthedTeamRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/welcome': {
      id: '/_authed/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthedWelcomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/$agentId': {
      id: '/_authed/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthedAgentsAgentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/$agentId/': {
      id: '/_authed/agents/$agentId/'
      path: '/'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AuthedAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthedAgentsAgentIdRoute
    }
    '/_authed/agents/$agentId/chat': {
      id: '/_authed/agents/$agentId/chat'
      path: '/chat'
      fullPath: '/agents/$agentId/chat'
      preLoaderRoute: typeof AuthedAgentsAgentIdChatRouteImport
      parentRoute: typeof AuthedAgentsAgentIdRoute
    }
    '/_authed/agents/$agentId/configuration': {
      id: '/_authed/agents/$agentId/configuration'
      path: '/configuration'
      fullPath: '/agents/$agentId/configuration'
      preLoaderRoute: typeof AuthedAgentsAgentIdConfigurationRouteImport
      parentRoute: typeof AuthedAgentsAgentIdRoute
    }
    '/_authed/agents/$agentId/knowledge': {
      id: '/_authed/agents/$agentId/knowledge'
      path: '/knowledge'
      fullPath: '/agents/$agentId/knowledge'
      preLoaderRoute: typeof AuthedAgentsAgentIdKnowledgeRouteImport
      parentRoute: typeof AuthedAgentsAgentIdRoute
    }
    '/_authed/agents/$agentId/settings': {
      id: '/_authed/agents/$agentId/settings'
      path: '/settings'
      fullPath: '/agents/$agentId/settings'
      preLoaderRoute: typeof AuthedAgentsAgentIdSettingsRouteImport
      parentRoute: typeof AuthedAgentsAgentIdRoute
    }
    '/_authed/agents/$agentId/routines/': {
      id: '/_authed/agents/$agentId/routines/'
      path: '/routines'
      fullPath: '/agents/$agentId/routines/'
      preLoaderRoute: typeof AuthedAgentsAgentIdRoutinesIndexRouteImport
      parentRoute: typeof AuthedAgentsAgentIdRoute
    }
    '/_authed/agents/$agentId/routines/$routineId': {
      id: '/_authed/agents/$agentId/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/agents/$agentId/routines/$routineId'
      preLoaderRoute: typeof AuthedAgentsAgentIdRoutinesRoutineIdRouteImport
      parentRoute: typeof AuthedAgentsAgentIdRoute
    }
  }
}

interface AuthedAgentsAgentIdRouteChildren {
  AuthedAgentsAgentIdChatRoute: typeof AuthedAgentsAgentIdChatRoute
  AuthedAgentsAgentIdConfigurationRoute: typeof AuthedAgentsAgentIdConfigurationRoute
  AuthedAgentsAgentIdKnowledgeRoute: typeof AuthedAgentsAgentIdKnowledgeRoute
  AuthedAgentsAgentIdSettingsRoute: typeof AuthedAgentsAgentIdSettingsRoute
  AuthedAgentsAgentIdIndexRoute: typeof AuthedAgentsAgentIdIndexRoute
  AuthedAgentsAgentIdRoutinesRoutineIdRoute: typeof AuthedAgentsAgentIdRoutinesRoutineIdRoute
  AuthedAgentsAgentIdRoutinesIndexRoute: typeof AuthedAgentsAgentIdRoutinesIndexRoute
}

const AuthedAgentsAgentIdRouteChildren: AuthedAgentsAgentIdRouteChildren = {
  AuthedAgentsAgentIdChatRoute: AuthedAgentsAgentIdChatRoute,
  AuthedAgentsAgentIdConfigurationRoute: AuthedAgentsAgentIdConfigurationRoute,
  AuthedAgentsAgentIdKnowledgeRoute: AuthedAgentsAgentIdKnowledgeRoute,
  AuthedAgentsAgentIdSettingsRoute: AuthedAgentsAgentIdSettingsRoute,
  AuthedAgentsAgentIdIndexRoute: AuthedAgentsAgentIdIndexRoute,
  AuthedAgentsAgentIdRoutinesRoutineIdRoute:
    AuthedAgentsAgentIdRoutinesRoutineIdRoute,
  AuthedAgentsAgentIdRoutinesIndexRoute: AuthedAgentsAgentIdRoutinesIndexRoute,
}

const AuthedAgentsAgentIdRouteWithChildren =
  AuthedAgentsAgentIdRoute._addFileChildren(AuthedAgentsAgentIdRouteChildren)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRoute
  AuthedIntegrationsRoute: typeof AuthedIntegrationsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTeamRoute: typeof AuthedTeamRoute
  AuthedWelcomeRoute: typeof AuthedWelcomeRoute
  AuthedAgentsAgentIdRoute: typeof AuthedAgentsAgentIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRoute,
  AuthedIntegrationsRoute: AuthedIntegrationsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTeamRoute: AuthedTeamRoute,
  AuthedWelcomeRoute: AuthedWelcomeRoute,
  AuthedAgentsAgentIdRoute: AuthedAgentsAgentIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ConfirmedRoute: ConfirmedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
